
server:
  port: 8001
  servlet:
    context-path: / # 기본 /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#springdoc: 
#  swagger-ui: 
#    path: /swagger-ui.html


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /jsp/
      suffix: .jsp

  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    view-names: thymeleaf/*

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/analysis?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: analysis
    password: analysis
    
    
#  jackson:
#    serialization:
#      fail-on-empty-beans: false